backend:
  name: github
  repo: Alexfd89/gatsby-blog

media_folder: static/img

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "blog" }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: author, label: Author }
      - { name: image, label: Image,  widget: image }
      - { name: body, label: Body, widget: markdown }

  - name: news
    label: News
    folder: src/pages/news
    create: true
    fields:
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "news" }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: author, label: Author, widget: "hidden" }
      - { name: body, label: Body, widget: markdown }